### PR TITLE
Upgrade to V0.7

### PR DESCRIPTION
**Pull request by FlorisHoogenboom**
Fix for https://github.com/bigdong89/xgboostExtension/issues/4.

### CODE REVIEW

**Comment by FlorisHoogenboom** [comment]
@bigdong89 I was wondering whether you  already have a chance to take a look at this? Thnx!

**Comment by bigdong89** [comment]
Good work!
Sorry for the late reply. I have just come back from my Spring Festival vocation.

**Comment by FlorisHoogenboom** [comment]
No worries! Thnx for the merge! Will you also publish the new version to PyPi again?

**Comment by bigdong89** [comment]
0.7 for Python 2 has been published to pypi. dongjiaquan89 邮箱：dongjiaquan89@gmail.com 签名由 网易邮箱大师 定制 On 02/22/2018 20:44, Floris Hoogenboom wrote: No worries! Thnx for the merge! Will you also publish the new version to PyPi again? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

**Pull request merged**
